import { ApiProperty } from '@nestjs/swagger';
import { AdminLoanApplicationEventDto } from './admin-loan-application-event.dto';

class AdminDisbursementDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  amount!: string;

  @ApiProperty()
  currency!: string;

  @ApiProperty()
  method!: string;

  @ApiProperty({ enum: ['PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REVERSED'] })
  status!: 'PENDING' | 'PROCESSING' | 'SUCCESS' | 'FAILED' | 'REVERSED';

  @ApiProperty({ nullable: true })
  provider!: string | null;

  @ApiProperty({ nullable: true })
  providerReference!: string | null;

  @ApiProperty({ nullable: true })
  reference!: string | null;

  @ApiProperty({ nullable: true })
  disbursedAt!: string | null;

  @ApiProperty({ nullable: true })
  processedAt!: string | null;

  @ApiProperty({ nullable: true })
  failureReason!: string | null;

  @ApiProperty()
  idempotencyKey!: string;
}

class AdminRepaymentDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  amount!: string;

  @ApiProperty()
  currency!: string;

  @ApiProperty()
  method!: string;

  @ApiProperty({ nullable: true })
  reference!: string | null;

  @ApiProperty()
  paidAt!: string;
}

class AdminRepaymentScheduleDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  installmentNo!: number;

  @ApiProperty()
  dueDate!: string;

  @ApiProperty()
  principalDue!: string;

  @ApiProperty()
  interestDue!: string;

  @ApiProperty()
  feesDue!: string;

  @ApiProperty()
  totalDue!: string;

  @ApiProperty({ enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE'] })
  status!: 'PENDING' | 'PARTIAL' | 'PAID' | 'OVERDUE';

  @ApiProperty({ nullable: true })
  paidAt!: string | null;

  @ApiProperty()
  isOverdue!: boolean;

  @ApiProperty({ nullable: true })
  overdueSince!: string | null;

  @ApiProperty()
  remainingAmountCents!: string;
}

class AdminLedgerLineDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  accountCode!: string;

  @ApiProperty({ enum: ['DEBIT', 'CREDIT'] })
  direction!: 'DEBIT' | 'CREDIT';

  @ApiProperty()
  amount!: string;
}

class AdminLedgerEntryDto {
  @ApiProperty()
  id!: string;

  @ApiProperty({ enum: ['DISBURSEMENT', 'REPAYMENT', 'ACCRUAL', 'WRITE_OFF', 'ADJUSTMENT'] })
  type!: 'DISBURSEMENT' | 'REPAYMENT' | 'ACCRUAL' | 'WRITE_OFF' | 'ADJUSTMENT';

  @ApiProperty()
  occurredAt!: string;

  @ApiProperty()
  idempotencyKey!: string;

  @ApiProperty()
  memo!: string | null;

  @ApiProperty({ type: [AdminLedgerLineDto] })
  lines!: AdminLedgerLineDto[];
}

class AdminCollectionActivityDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  actionType!: string;

  @ApiProperty({ nullable: true })
  note!: string | null;

  @ApiProperty()
  performedBy!: string;

  @ApiProperty()
  createdAt!: string;
}

class InterestAccrualAuditDto {
  @ApiProperty()
  id!: string;

  @ApiProperty({ enum: ['PAUSED', 'RESUMED', 'RATE_OVERRIDE_SET', 'RATE_OVERRIDE_REMOVED'] })
  action!: 'PAUSED' | 'RESUMED' | 'RATE_OVERRIDE_SET' | 'RATE_OVERRIDE_REMOVED';

  @ApiProperty({ nullable: true })
  previousRate!: string | null;

  @ApiProperty({ nullable: true })
  newRate!: string | null;

  @ApiProperty({ nullable: true })
  reason!: string | null;

  @ApiProperty()
  performedById!: string;

  @ApiProperty()
  createdAt!: string;
}

class AdminDecisionEventDto {
  @ApiProperty()
  id!: string;

  @ApiProperty({ enum: ['APPROVE', 'MANUAL_REVIEW', 'DECLINE'] })
  decision!: 'APPROVE' | 'MANUAL_REVIEW' | 'DECLINE';

  @ApiProperty({ type: [String] })
  reasonCodes!: string[];

  @ApiProperty({ enum: ['SYSTEM', 'ADMIN'] })
  actorType!: 'SYSTEM' | 'ADMIN';

  @ApiProperty({ nullable: true })
  actorId!: string | null;

  @ApiProperty({ nullable: true })
  actorRole!: string | null;

  @ApiProperty()
  createdAt!: string;

  @ApiProperty({ nullable: true })
  inputsJson!: unknown;

  @ApiProperty({ nullable: true })
  recommendedLimit!: string | null;

  @ApiProperty({ nullable: true })
  recommendedTenorDays!: number | null;
}

class AdminFraudSignalEventDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  signalType!: string;

  @ApiProperty({ enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] })
  severity!: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

  @ApiProperty({ nullable: true })
  metadataJson!: unknown;

  @ApiProperty()
  createdAt!: string;
}

class AdminFraudAlertDto {
  @ApiProperty()
  id!: string;

  @ApiProperty({ enum: ['OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', 'ESCALATED'] })
  status!: 'OPEN' | 'INVESTIGATING' | 'RESOLVED' | 'FALSE_POSITIVE' | 'ESCALATED';

  @ApiProperty({ enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] })
  severity!: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

  @ApiProperty()
  autoGenerated!: boolean;

  @ApiProperty({ nullable: true })
  resolutionNotes!: string | null;

  @ApiProperty({ nullable: true })
  resolvedAt!: string | null;

  @ApiProperty()
  createdAt!: string;
}

class IdentityVerificationDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  provider!: string;

  @ApiProperty({ enum: ['PENDING', 'VERIFIED', 'FAILED', 'MANUAL_REVIEW'] })
  status!: 'PENDING' | 'VERIFIED' | 'FAILED' | 'MANUAL_REVIEW';

  @ApiProperty({ nullable: true })
  matchScore!: number | null;

  @ApiProperty({ nullable: true })
  riskFlags!: unknown;

  @ApiProperty()
  createdAt!: string;
}

export class AdminLoanApplicationDetailsDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  tenantId!: string;

  @ApiProperty({ enum: ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REQUESTED_DOCUMENTS', 'APPROVED', 'READY_FOR_DISBURSEMENT', 'DISBURSED', 'OVERDUE', 'WRITTEN_OFF', 'SETTLED', 'REPAID', 'DEFAULTED', 'REJECTED'] })
  status!: 'DRAFT' | 'SUBMITTED' | 'UNDER_REVIEW' | 'REQUESTED_DOCUMENTS' | 'APPROVED' | 'READY_FOR_DISBURSEMENT' | 'DISBURSED' | 'OVERDUE' | 'WRITTEN_OFF' | 'SETTLED' | 'REPAID' | 'DEFAULTED' | 'REJECTED';

  @ApiProperty()
  fullName!: string;

  @ApiProperty()
  phone!: string;

  @ApiProperty({ nullable: true })
  email!: string | null;

  @ApiProperty({ nullable: true })
  dob!: string | null;

  @ApiProperty({ nullable: true })
  address!: string | null;

  @ApiProperty()
  amount!: number;

  @ApiProperty()
  tenorMonths!: number;

  @ApiProperty({ nullable: true })
  purpose!: string | null;

  @ApiProperty({ nullable: true })
  employmentStatus!: string | null;

  @ApiProperty({ nullable: true })
  incomeBand!: string | null;

  @ApiProperty()
  requestedAmount!: string;

  @ApiProperty({ nullable: true })
  approvedAmount!: string | null;

  @ApiProperty({ nullable: true })
  disbursedAmount!: string | null;

  @ApiProperty()
  outstandingPrincipal!: string;

  @ApiProperty()
  outstandingInterest!: string;

  @ApiProperty()
  outstandingFees!: string;

  @ApiProperty()
  totalOutstanding!: string;

  @ApiProperty({ enum: ['CURRENT', 'OVERDUE', 'CHARGED_OFF'] })
  delinquencyStatus!: 'CURRENT' | 'OVERDUE' | 'CHARGED_OFF';

  @ApiProperty()
  daysPastDue!: number;

  @ApiProperty()
  overdueAmountCents!: string;

  @ApiProperty({ nullable: true })
  lastDelinquencyCalcAt!: string | null;

  @ApiProperty({ nullable: true })
  annualInterestRate!: string | null;

  @ApiProperty()
  interestAccrualPaused!: boolean;

  @ApiProperty({ nullable: true })
  interestPausedAt!: string | null;

  @ApiProperty({ nullable: true })
  interestPausedById!: string | null;

  @ApiProperty({ nullable: true })
  interestPauseReason!: string | null;

  @ApiProperty({ nullable: true })
  interestOverrideRate!: string | null;

  @ApiProperty({ nullable: true })
  interestOverrideSetAt!: string | null;

  @ApiProperty({ nullable: true })
  interestOverrideSetById!: string | null;

  @ApiProperty({ nullable: true })
  lastAccruedAt!: string | null;

  @ApiProperty()
  createdAt!: string;

  @ApiProperty()
  updatedAt!: string;

  @ApiProperty({ type: [AdminLoanApplicationEventDto] })
  histories!: AdminLoanApplicationEventDto[];

  @ApiProperty({ type: AdminDisbursementDto, nullable: true })
  disbursement!: AdminDisbursementDto | null;

  @ApiProperty({ type: [AdminRepaymentDto] })
  repayments!: AdminRepaymentDto[];

  @ApiProperty({ type: [AdminRepaymentScheduleDto] })
  schedule!: AdminRepaymentScheduleDto[];

  @ApiProperty({ type: [AdminCollectionActivityDto] })
  collectionActivities!: AdminCollectionActivityDto[];

  @ApiProperty({ type: [InterestAccrualAuditDto] })
  interestAccrualAudits!: InterestAccrualAuditDto[];

  @ApiProperty({ type: [AdminLedgerEntryDto] })
  ledgerEntries!: AdminLedgerEntryDto[];

  @ApiProperty({ type: [AdminDecisionEventDto] })
  decisionEvents!: AdminDecisionEventDto[];

  @ApiProperty({ type: [AdminFraudSignalEventDto] })
  fraudSignals!: AdminFraudSignalEventDto[];

  @ApiProperty({ type: [AdminFraudAlertDto] })
  fraudAlerts!: AdminFraudAlertDto[];

  @ApiProperty({ type: IdentityVerificationDto, nullable: true })
  identityVerification!: IdentityVerificationDto | null;
}
