export const PERMISSIONS = [
  'LOANS_APPROVE',
  'DISBURSEMENTS_MANAGE',
  'BORROWERS_READ',
  'BORROWERS_WRITE',
  'UNDERWRITING_EDIT',
  'AUDIT_EXPORT',
  'JOBS_RETRY',
  'ROLES_VIEW',
  'ADMIN_USERS_ROLE_ASSIGN',
  'LENDER_SETTINGS_EDIT',
  'ADMIN_USERS_VIEW',
  'ADMIN_USERS_MANAGE',
  'REPORTS_VIEW',
  'RISK_VIEW'
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const DEFAULT_ROLE_PERMISSION_MAP: Record<'OWNER' | 'OPS' | 'FINANCE' | 'VIEWER', PermissionCode[]> = {
  OWNER: [...PERMISSIONS],
  OPS: [
    'LOANS_APPROVE',
    'DISBURSEMENTS_MANAGE',
    'BORROWERS_READ',
    'BORROWERS_WRITE',
    'UNDERWRITING_EDIT',
    'JOBS_RETRY',
    'ROLES_VIEW',
    'ADMIN_USERS_VIEW',
    'ADMIN_USERS_MANAGE',
    'REPORTS_VIEW',
    'RISK_VIEW'
  ],
  FINANCE: [
    'LOANS_APPROVE',
    'DISBURSEMENTS_MANAGE',
    'BORROWERS_READ',
    'AUDIT_EXPORT',
    'ROLES_VIEW',
    'ADMIN_USERS_VIEW',
    'REPORTS_VIEW',
    'RISK_VIEW'
  ],
  VIEWER: ['BORROWERS_READ', 'ROLES_VIEW', 'ADMIN_USERS_VIEW', 'REPORTS_VIEW', 'RISK_VIEW']
};
