-- Ledger engine hardening (tenant ledger)

ALTER TYPE "TenantLedgerEntryType" ADD VALUE IF NOT EXISTS 'WRITE_OFF';

ALTER TYPE "TenantLedgerAccountCode" ADD VALUE IF NOT EXISTS 'CASH_MAIN';
ALTER TYPE "TenantLedgerAccountCode" ADD VALUE IF NOT EXISTS 'LOANS_RECEIVABLE';
ALTER TYPE "TenantLedgerAccountCode" ADD VALUE IF NOT EXISTS 'PENALTY_INCOME';
ALTER TYPE "TenantLedgerAccountCode" ADD VALUE IF NOT EXISTS 'WRITE_OFF_EXPENSE';

ALTER TABLE "TenantLedgerAccount"
ADD COLUMN IF NOT EXISTS "type" "LedgerAccountType" NOT NULL DEFAULT 'ASSET',
ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'NGN',
ADD COLUMN IF NOT EXISTS "isSystem" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "TenantLedgerEntry"
ADD COLUMN IF NOT EXISTS "createdBy" TEXT,
ADD COLUMN IF NOT EXISTS "reversalOfEntryId" TEXT;

ALTER TABLE "TenantLedgerLine"
ADD COLUMN IF NOT EXISTS "amountMinor" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'NGN';

CREATE UNIQUE INDEX IF NOT EXISTS "TenantLedgerAccount_tenantId_name_key"
ON "TenantLedgerAccount"("tenantId", "name");

