ALTER TYPE "TenantAdminRole" ADD VALUE IF NOT EXISTS 'CREDIT_OFFICER';
ALTER TYPE "TenantAdminRole" ADD VALUE IF NOT EXISTS 'RISK_MANAGER';
ALTER TYPE "TenantAdminRole" ADD VALUE IF NOT EXISTS 'OPS';
ALTER TYPE "TenantAdminRole" ADD VALUE IF NOT EXISTS 'COLLECTIONS';
ALTER TYPE "TenantAdminRole" ADD VALUE IF NOT EXISTS 'SYSTEM';
