-- CreateEnum
CREATE TYPE "FraudSignalType" AS ENUM (
  'MULTIPLE_APPLICATIONS_SHORT_WINDOW',
  'DEVICE_MISMATCH',
  'HIGH_RISK_SCORE',
  'REPAYMENT_PATTERN_ANOMALY',
  'GEO_MISMATCH',
  'MANUAL_FLAG'
);

-- CreateEnum
CREATE TYPE "FraudSeverity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "FraudAlertStatus" AS ENUM ('OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', 'ESCALATED');

-- CreateTable
CREATE TABLE "FraudSignal" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "borrowerId" TEXT,
    "loanApplicationId" TEXT,
    "type" "FraudSignalType" NOT NULL,
    "severity" "FraudSeverity" NOT NULL,
    "scoreImpact" INTEGER NOT NULL,
    "metadataJson" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FraudSignal_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FraudAlert" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "borrowerId" TEXT,
    "loanApplicationId" TEXT,
    "status" "FraudAlertStatus" NOT NULL DEFAULT 'OPEN',
    "severity" "FraudSeverity" NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "resolvedBy" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "resolutionNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "FraudAlert_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FraudAlertSignal" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "fraudAlertId" TEXT NOT NULL,
    "fraudSignalId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FraudAlertSignal_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BorrowerBehaviorSnapshot" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "borrowerId" TEXT NOT NULL,
    "totalApplications" INTEGER NOT NULL DEFAULT 0,
    "totalApproved" INTEGER NOT NULL DEFAULT 0,
    "totalRejected" INTEGER NOT NULL DEFAULT 0,
    "totalDisbursedAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "totalRepaidAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "defaultCount" INTEGER NOT NULL DEFAULT 0,
    "lastApplicationAt" TIMESTAMP(3),
    "lastRepaymentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BorrowerBehaviorSnapshot_pkey" PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "FraudSignal_tenantId_idx" ON "FraudSignal"("tenantId");
CREATE INDEX "FraudSignal_tenantId_loanApplicationId_idx" ON "FraudSignal"("tenantId", "loanApplicationId");
CREATE INDEX "FraudSignal_tenantId_borrowerId_idx" ON "FraudSignal"("tenantId", "borrowerId");
CREATE INDEX "FraudSignal_tenantId_createdAt_idx" ON "FraudSignal"("tenantId", "createdAt");

CREATE INDEX "FraudAlert_tenantId_status_severity_idx" ON "FraudAlert"("tenantId", "status", "severity");
CREATE INDEX "FraudAlert_tenantId_loanApplicationId_idx" ON "FraudAlert"("tenantId", "loanApplicationId");
CREATE INDEX "FraudAlert_tenantId_borrowerId_idx" ON "FraudAlert"("tenantId", "borrowerId");
CREATE INDEX "FraudAlert_tenantId_createdAt_idx" ON "FraudAlert"("tenantId", "createdAt");

CREATE UNIQUE INDEX "FraudAlertSignal_fraudAlertId_fraudSignalId_key" ON "FraudAlertSignal"("fraudAlertId", "fraudSignalId");
CREATE INDEX "FraudAlertSignal_tenantId_fraudAlertId_idx" ON "FraudAlertSignal"("tenantId", "fraudAlertId");

CREATE UNIQUE INDEX "BorrowerBehaviorSnapshot_tenantId_borrowerId_key" ON "BorrowerBehaviorSnapshot"("tenantId", "borrowerId");
CREATE INDEX "BorrowerBehaviorSnapshot_tenantId_updatedAt_idx" ON "BorrowerBehaviorSnapshot"("tenantId", "updatedAt");

-- FKs
ALTER TABLE "FraudSignal"
  ADD CONSTRAINT "FraudSignal_loanApplicationId_fkey"
  FOREIGN KEY ("loanApplicationId") REFERENCES "TenantLoanApplication"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "FraudAlert"
  ADD CONSTRAINT "FraudAlert_loanApplicationId_fkey"
  FOREIGN KEY ("loanApplicationId") REFERENCES "TenantLoanApplication"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "FraudAlertSignal"
  ADD CONSTRAINT "FraudAlertSignal_fraudAlertId_fkey"
  FOREIGN KEY ("fraudAlertId") REFERENCES "FraudAlert"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "FraudAlertSignal"
  ADD CONSTRAINT "FraudAlertSignal_fraudSignalId_fkey"
  FOREIGN KEY ("fraudSignalId") REFERENCES "FraudSignal"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

