import { BadRequestException, Body, Controller, Get, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { FraudLevel, HoldStatus, TenantAdminRole } from '@prisma/client';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import { TenantAdminAuthGuard } from '../admin-auth/guards/tenant-admin-auth.guard';
import { CurrentTenantAdmin } from '../../common/auth/current-tenant-admin.decorator';
import type { TenantAdminPrincipal } from '../../common/auth/tenant-admin-principal';
import { AuditService } from '../../common/audit/audit.service';
import { PrismaService } from '../../common/database/prisma.service';
import { parsePagination } from '../../common/http/pagination';
import { FraudEvaluatorService } from './fraud-evaluator.service';
import { FraudRulesService } from './fraud-rules.service';
import { FraudScoringService } from './fraud-scoring.service';
import { RiskEventService } from './risk-event.service';
import {
  fraudBorrowerHoldBodySchema,
  fraudQueueQuerySchema,
  listFraudAlertsQuerySchema,
  manualFraudFlagSchema,
  updateFraudAlertSchema
} from './dto/admin-fraud.dto';

function canManageBorrowerHold(role: TenantAdminRole): boolean {
  return role === 'SUPER_ADMIN' || role === 'RISK_MANAGER' || role === 'SYSTEM';
}

@ApiTags('Admin Fraud')
@ApiBearerAuth('bearer')
@Controller('admin/fraud')
@UseGuards(TenantAdminAuthGuard)
export class AdminFraudController {
  constructor(
    private readonly fraudService: FraudEvaluatorService,
    private readonly fraudScoringService: FraudScoringService,
    private readonly fraudRulesService: FraudRulesService,
    private readonly riskEventService: RiskEventService,
    private readonly auditService: AuditService,
    private readonly prisma: PrismaService
  ) {}

  @Get('alerts')
  @ApiOperation({ summary: 'List fraud alerts for tenant' })
  async listAlerts(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Query() query: Record<string, string | undefined>
  ) {
    const parsed = listFraudAlertsQuerySchema.safeParse(query);
    if (!parsed.success) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Invalid fraud alerts query.',
        details: parsed.error.flatten()
      });
    }
    const rows = await this.fraudService.listAlerts({
      tenantId: principal.tenantId,
      status: parsed.data.status,
      severity: parsed.data.severity,
      onlyOpen: parsed.data.onlyOpen
    });
    return rows.map((row: any) => ({
      id: row.id,
      tenantId: row.tenantId,
      borrowerId: row.borrowerId,
      loanApplicationId: row.loanApplicationId,
      status: row.status,
      severity: row.severity,
      autoGenerated: row.autoGenerated,
      resolvedBy: row.resolvedBy,
      resolvedAt: row.resolvedAt?.toISOString() ?? null,
      resolutionNotes: row.resolutionNotes ?? null,
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString()
    }));
  }

  @Get('alerts/:id')
  @ApiOperation({ summary: 'Get fraud alert details with linked signals' })
  async getAlert(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Param('id') id: string
  ) {
    const row = await this.fraudService.getAlert(principal.tenantId, id);
    return {
      id: row.id,
      tenantId: row.tenantId,
      borrowerId: row.borrowerId,
      loanApplicationId: row.loanApplicationId,
      status: row.status,
      severity: row.severity,
      autoGenerated: row.autoGenerated,
      resolvedBy: row.resolvedBy,
      resolvedAt: row.resolvedAt?.toISOString() ?? null,
      resolutionNotes: row.resolutionNotes ?? null,
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
      signals: row.signals.map((item: any) => ({
        id: item.fraudSignal.id,
        type: item.fraudSignal.type,
        severity: item.fraudSignal.severity,
        scoreImpact: item.fraudSignal.scoreImpact,
        metadataJson: item.fraudSignal.metadataJson,
        createdAt: item.fraudSignal.createdAt.toISOString()
      }))
    };
  }

  @Patch('alerts/:id')
  @ApiOperation({ summary: 'Update fraud alert status' })
  async updateAlert(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Param('id') id: string,
    @Body() body: unknown
  ) {
    const parsed = updateFraudAlertSchema.safeParse(body);
    if (!parsed.success) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Invalid fraud alert update payload.',
        details: parsed.error.flatten()
      });
    }
    const updated = await this.fraudService.updateAlertStatus({
      tenantId: principal.tenantId,
      alertId: id,
      status: parsed.data.status,
      actorAdminId: principal.adminId,
      resolutionNotes: parsed.data.resolutionNotes
    });
    await this.auditService.log({
      tenantId: principal.tenantId,
      actorType: 'TENANT_ADMIN',
      actorId: principal.adminId,
      actorRole: principal.role,
      action: 'FRAUD_ALERT_STATUS_UPDATED',
      entity: 'FRAUD_ALERT',
      entityId: updated.id,
      metadata: {
        status: updated.status,
        resolutionNotes: parsed.data.resolutionNotes ?? null
      }
    });
    return {
      id: updated.id,
      status: updated.status,
      resolutionNotes: updated.resolutionNotes ?? null,
      resolvedAt: updated.resolvedAt?.toISOString() ?? null
    };
  }

  @Post('loan-applications/:id/manual-flag')
  @ApiOperation({ summary: 'Create a manual fraud flag for a loan application' })
  async createManualFlag(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Param('id') loanApplicationId: string,
    @Body() body: unknown
  ) {
    const parsed = manualFraudFlagSchema.safeParse(body);
    if (!parsed.success) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Invalid manual fraud flag payload.',
        details: parsed.error.flatten()
      });
    }
    const result = await this.fraudService.createManualFlag({
      tenantId: principal.tenantId,
      loanApplicationId,
      adminId: principal.adminId,
      note: parsed.data.note,
      severity: parsed.data.severity
    });
    await this.auditService.log({
      tenantId: principal.tenantId,
      actorType: 'TENANT_ADMIN',
      actorId: principal.adminId,
      actorRole: principal.role,
      action: 'FRAUD_MANUAL_FLAG_CREATED',
      entity: 'TENANT_LOAN_APPLICATION',
      entityId: loanApplicationId,
      metadata: {
        signalId: result.signalId,
        alertId: result.alertId ?? null,
        severity: parsed.data.severity ?? 'HIGH'
      }
    });
    return result;
  }

  @Get('queue')
  @ApiOperation({ summary: 'List borrower fraud queue by level (HIGH or SEVERE)' })
  async queue(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Query() query: Record<string, string | undefined>
  ) {
    const parsed = fraudQueueQuerySchema.safeParse(query);
    if (!parsed.success) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Invalid fraud queue query.',
        details: parsed.error.flatten()
      });
    }

    const levels = parsed.data.level ? [parsed.data.level] : ['HIGH', 'SEVERE'];
    const pagination = parsePagination(parsed.data);
    const rows = await this.prisma.fraudSignalAggregate.findMany({
      where: {
        tenantId: principal.tenantId,
        fraudLevel: { in: levels as FraudLevel[] }
      },
      orderBy: [{ fraudLevel: 'desc' }, { updatedAt: 'desc' }],
      take: pagination.take,
      skip: pagination.skip,
      cursor: pagination.cursor
    });

    const borrowerIds = [...new Set(rows.map((row) => row.borrowerId).filter(Boolean))];
    const borrowerMetaRows = borrowerIds.length
      ? await this.prisma.tenantLoanApplication.findMany({
          where: {
            tenantId: principal.tenantId,
            phone: { in: borrowerIds }
          },
          select: {
            phone: true,
            fullName: true,
            createdAt: true
          },
          orderBy: { createdAt: 'desc' }
        })
      : [];
    const borrowerMeta = new Map<string, { fullName: string | null; phone: string }>();
    for (const row of borrowerMetaRows) {
      if (!borrowerMeta.has(row.phone)) {
        borrowerMeta.set(row.phone, { fullName: row.fullName ?? null, phone: row.phone });
      }
    }

    return {
      items: rows.map((row) => {
        const meta = borrowerMeta.get(row.borrowerId);
        return {
          id: row.id,
          tenantId: row.tenantId,
          borrowerId: row.borrowerId,
          borrowerName: meta?.fullName ?? null,
          borrowerPhone: meta?.phone ?? row.borrowerId,
          riskScore: row.riskScore,
          fraudLevel: row.fraudLevel,
          flags: row.flags,
          lastEvaluatedAt: row.lastEvaluatedAt?.toISOString() ?? null,
          updatedAt: row.updatedAt.toISOString()
        };
      })
    };
  }

  @Get('borrowers/:borrowerId')
  @ApiOperation({ summary: 'Get borrower fraud detail: aggregate + recent events + holds' })
  async borrowerDetail(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Param('borrowerId') borrowerId: string
  ) {
    const normalizedBorrowerId = borrowerId.trim();
    const aggregate = await this.fraudScoringService.evaluateBorrower(principal.tenantId, normalizedBorrowerId);
    const [events, holds, borrowerRecord] = await Promise.all([
      this.prisma.fraudSignal.findMany({
        where: {
          tenantId: principal.tenantId,
          borrowerId: normalizedBorrowerId
        },
        orderBy: { createdAt: 'desc' },
        take: 100
      }),
      this.prisma.borrowerHold.findMany({
        where: {
          tenantId: principal.tenantId,
          borrowerId: normalizedBorrowerId
        },
        orderBy: { createdAt: 'desc' },
        take: 20
      }),
      this.prisma.tenantLoanApplication.findFirst({
        where: {
          tenantId: principal.tenantId,
          phone: normalizedBorrowerId
        },
        orderBy: { createdAt: 'desc' },
        select: {
          fullName: true,
          phone: true,
          email: true
        }
      })
    ]);

    return {
      aggregate: {
        id: aggregate.aggregate.id,
        tenantId: aggregate.aggregate.tenantId,
        borrowerId: aggregate.aggregate.borrowerId,
        riskScore: aggregate.aggregate.riskScore,
        fraudLevel: aggregate.aggregate.fraudLevel,
        flags: aggregate.aggregate.flags,
        lastEvaluatedAt: aggregate.aggregate.lastEvaluatedAt?.toISOString() ?? null,
        updatedAt: aggregate.aggregate.updatedAt.toISOString()
      },
      borrower: {
        id: normalizedBorrowerId,
        fullName: borrowerRecord?.fullName ?? null,
        phone: borrowerRecord?.phone ?? normalizedBorrowerId,
        email: borrowerRecord?.email ?? null
      },
      recentEvents: events.map((row) => ({
        id: row.id,
        type: row.type,
        severity: row.severity,
        source: row.source,
        scoreImpact: row.scoreImpact,
        metadataJson: row.metadataJson,
        createdAt: row.createdAt.toISOString()
      })),
      holds: holds.map((row) => ({
        id: row.id,
        status: row.status,
        reason: row.reason,
        createdByAdminId: row.createdByAdminId,
        createdBySystem: row.createdBySystem,
        releasedAt: row.releasedAt?.toISOString() ?? null,
        releaseReason: row.releaseReason ?? null,
        createdAt: row.createdAt.toISOString()
      })),
      counters: aggregate.counters
    };
  }

  @Post('borrowers/:borrowerId/hold')
  @ApiOperation({ summary: 'Create manual borrower hold' })
  async holdBorrower(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Param('borrowerId') borrowerId: string,
    @Body() body: unknown
  ) {
    if (!canManageBorrowerHold(principal.role)) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Role cannot create borrower hold.',
        details: null
      });
    }
    const parsed = fraudBorrowerHoldBodySchema.safeParse(body);
    if (!parsed.success) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Invalid borrower hold payload.',
        details: parsed.error.flatten()
      });
    }
    const hold = await this.fraudRulesService.createHold({
      tenantId: principal.tenantId,
      borrowerId: borrowerId.trim(),
      reason: parsed.data.reason,
      createdByAdminId: principal.adminId,
      createdBySystem: false
    });
    await this.riskEventService.createEvent(principal.tenantId, {
      borrowerId: borrowerId.trim(),
      type: 'MANUAL_REVIEW_REQUESTED',
      severity: 'HIGH',
      source: 'admin',
      meta: {
        reason: parsed.data.reason,
        action: 'HOLD_CREATED',
        holdId: hold.id
      }
    });
    await this.auditService.log({
      tenantId: principal.tenantId,
      actorType: 'TENANT_ADMIN',
      actorId: principal.adminId,
      actorRole: principal.role,
      action: 'FRAUD_BORROWER_HOLD_CREATED',
      entity: 'BORROWER_HOLD',
      entityId: hold.id,
      metadata: {
        borrowerId: borrowerId.trim(),
        reason: parsed.data.reason,
        status: hold.status
      }
    });
    return {
      id: hold.id,
      tenantId: hold.tenantId,
      borrowerId: hold.borrowerId,
      status: hold.status,
      reason: hold.reason,
      createdByAdminId: hold.createdByAdminId,
      createdBySystem: hold.createdBySystem,
      createdAt: hold.createdAt.toISOString(),
      updatedAt: hold.updatedAt.toISOString()
    };
  }

  @Post('borrowers/:borrowerId/release')
  @ApiOperation({ summary: 'Release active borrower hold' })
  async releaseBorrowerHold(
    @CurrentTenantAdmin() principal: TenantAdminPrincipal,
    @Param('borrowerId') borrowerId: string,
    @Body() body: unknown
  ) {
    if (!canManageBorrowerHold(principal.role)) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Role cannot release borrower hold.',
        details: null
      });
    }
    const parsed = fraudBorrowerHoldBodySchema.safeParse(body);
    if (!parsed.success) {
      throw new BadRequestException({
        code: 'BAD_REQUEST',
        message: 'Invalid borrower hold release payload.',
        details: parsed.error.flatten()
      });
    }
    const hold = await this.fraudRulesService.releaseHold({
      tenantId: principal.tenantId,
      borrowerId: borrowerId.trim(),
      adminId: principal.adminId,
      reason: parsed.data.reason
    });
    await this.riskEventService.createEvent(principal.tenantId, {
      borrowerId: borrowerId.trim(),
      type: 'ADMIN_OVERRIDE',
      severity: 'MEDIUM',
      source: 'admin',
      meta: {
        reason: parsed.data.reason,
        action: 'HOLD_RELEASED',
        holdId: hold.id
      }
    });
    await this.auditService.log({
      tenantId: principal.tenantId,
      actorType: 'TENANT_ADMIN',
      actorId: principal.adminId,
      actorRole: principal.role,
      action: 'FRAUD_BORROWER_HOLD_RELEASED',
      entity: 'BORROWER_HOLD',
      entityId: hold.id,
      metadata: {
        borrowerId: borrowerId.trim(),
        releaseReason: parsed.data.reason,
        status: hold.status
      }
    });
    return {
      id: hold.id,
      tenantId: hold.tenantId,
      borrowerId: hold.borrowerId,
      status: hold.status,
      reason: hold.reason,
      releasedAt: hold.releasedAt?.toISOString() ?? null,
      releaseReason: hold.releaseReason ?? null,
      updatedAt: hold.updatedAt.toISOString()
    };
  }
}
